# Generated by Django 2.2.3 on 2019-07-29 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_personalnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='subtitle',
            field=models.CharField(default='default subtitle', max_length=200),
        ),
    ]
